spring.application.name=CustomerService
server.port=8081

inventory.service.url=http://localhost:8080/actuator/health

spring.profiles.include=local

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
